### ISSUE TITLE
Crash in library when last element in view pager is deleted

### ISSUE THREAD

**Issue by CDRussell** [DavidPacioianu/InkPageIndicator#11]
In my project, I have to support the view pager being updated such that any page in it can be deleted.

The InkPageIndicator library crashes when I delete the final page with an `ArrayIndexOutOfBoundsException`

It looks like maybe `dotsToHide` isn't being updated at the right time and is always expecting 1 more than it has access to after deleting.

`java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
                                                                  at com.pixelcan.inkpageindicator.InkPageIndicator.setDotRevealFraction(InkPageIndicator.java:655)
                                                                  at com.pixelcan.inkpageindicator.InkPageIndicator.access$1600(InkPageIndicator.java:47)
                                                                  at com.pixelcan.inkpageindicator.InkPageIndicator$PendingRetreatAnimator$3.onAnimationStart(InkPageIndicator.java:765)
                                                                  at android.animation.ValueAnimator.notifyStartListeners(ValueAnimator.java:981)
                                                                  at android.animation.ValueAnimator.start(ValueAnimator.java:1043)
                                                                  at android.animation.ValueAnimator.start(ValueAnimator.java:1050)
                                                                  at com.pixelcan.inkpageindicator.InkPageIndicator$PendingStartAnimator.startIfNecessary(InkPageIndicator.java:681)
                                                                  at com.pixelcan.inkpageindicator.InkPageIndicator$3.onAnimationUpdate(InkPageIndicator.java:610)
                                                                  at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1374)
                                                                  at android.animation.ValueAnimator.animationFrame(ValueAnimator.java:1298)
                                                                  at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1339)
                                                                  at android.animation.ValueAnimator$AnimationHandler.doAnimationFrame(ValueAnimator.java:715)
                                                                  at android.animation.ValueAnimator$AnimationHandler.run(ValueAnimator.java:738)
                                                                  at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
                                                                  at android.view.Choreographer.doCallbacks(Choreographer.java:580)
                                                                  at android.view.Choreographer.doFrame(Choreographer.java:549)
                                                                  at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
                                                                  at android.os.Handler.handleCallback(Handler.java:739)
                                                                  at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                  at android.os.Looper.loop(Looper.java:135)
                                                                  at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                  at java.lang.reflect.Method.invoke(Method.java:372)
                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)`

**Comment by CDRussell** [comment]
I've forked and added a guard around the offending lines to let me progress using the library for now. I won't create a PR as I don't think it is the right fix; merely a stop gap to stop it blocking me.

https://github.com/CDRussell/InkPageIndicator/commit/d4bf75874624eccd77bbb9109146984b2d4710e8

**Comment by DavidPacioianu** [comment]
Thank you! I have just added your fix in the latest version.
